# Generated by Django 5.0 on 2024-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Терапия", "Терапия"),
                            (
                                "Хирургия/имплантация",
                                "Хирургическое лечение и имплантация",
                            ),
                            ("Ортопедия", "Ортопедическое лечение"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Терапия", "Терапия"),
                            (
                                "Хирургия/имплантация",
                                "Хирургическое лечение и имплантация",
                            ),
                            ("Ортопедия", "Ортопедическое лечение"),
                        ],
                        max_length=20,
                    ),
                ),
                ("testimonial", models.TextField()),
            ],
        ),
    ]
