# Generated by Django 5.0 on 2024-01-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_appointment_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
