# Generated by Django 5.0 on 2024-01-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_appointment_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(max_length=19),
        ),
    ]
