# Generated by Django 5.0 on 2024-01-26 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_appointment_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="date",
        ),
    ]
